### ISSUE TITLE
Form组件不支持style

### ISSUE THREAD

**Issue by JeanerK** [Kotomi-Team/kotomi-ui#106]
Stop Trying to Reinvent the Wheel, especially did bad jobs.

**Comment by jhoneybee** [comment]
推荐采用 https://ant.design/components/form-cn/

**Comment by jhoneybee** [comment]
Kotomi Ui的Form，的出发点是辅助初级开发者进行构建复杂的Form表单，所以它不支持响应式布局。

在开发一些项目中，我会收获很多的知识，收到鼓励我会很开心。 但是如果收到 `Stop Trying to Reinvent the Wheel, especially did bad jobs.` 我会非常难过。 

如果您是为了自己的项目，可以采用antd，  ag-gird , rc-form 做一些集成  。 这些都是非常棒的开源项目.
