### ISSUE TITLE
Table组件rowSelectedKeys属性无效

### ISSUE THREAD

**Issue by JeanerK** [Kotomi-Team/kotomi-ui#110]
往LinkTableExt中传入rowSelectedKeys，值为空数组，table展示的数据，之前选中的数据没有取消勾选，同时，取消选中后checkbox旁边的edit图标没有消失。版本1.7.8

**Comment by JeanerK** [comment]
版本1.7.8

**Comment by jhoneybee** [comment]
能否给一个最小化复现地址？

**Comment by jhoneybee** [comment]
七天未反馈，关闭此issues
