### ISSUE TITLE
Table组件在切换每页显示条数的时候，state中的pageSize没有更新

### ISSUE THREAD

**Issue by Yambo92** [Kotomi-Team/kotomi-ui#144]
Table组件在切换每页显示条数的时候onChange，state中的pageSize没有更新，导致行操作后再次重载数据的时候，每页还是显示的默认条数`<Pagination
                        className="kotomi-components-table-pagination"
                        size='small'
                        current={this.state.page}
                        total={this.state.total}
                        hideOnSinglePage
                        showSizeChanger
                        showQuickJumper
                        pageSizeOptions={this.props.pageSizeOptions}
                        defaultPageSize={this.props.defaultPageSize!}
                        onShowSizeChange={(page: number, pageSize?: number) => {
                            this.requestLoadData({
                                page,
                                pageSize: pageSize!,
                                sorter: {} as TableSorter,
                            })
                        }}
                        onChange={(page: number, pageSize?: number) => {
                            this.requestLoadData({
                                page,
                                pageSize: pageSize!,
                                sorter: {} as TableSorter,
                            })
                        }}
                    />`

**Comment by jhoneybee** [comment]
https://github.com/Kotomi-Team/kotomi-ui/pull/145

已经修复，非常感谢反馈
